// GENERATED by `npm run gsm` (tools/localeTools types). Do not edit.

export type Gsm = {
	_scale?: number
	/** en */
	_lang?: string
	_shortcut_screenshot?: boolean
	audio: {
		/** Release audio */
		releaseTab: string
		/** Split */
		split: string
		/** Control audio channels separately */
		splitTooltip: string
		/** Reverse audio */
		reverse: string
		/** Press and hold to record this tab's audio and play it back in reverse */
		reverseTooltip: string
		/** Equalizer */
		equalizer: string
		/** Better quality */
		pitchHdTooltip: string
		/** Recording */
		recording: string
		/** Playing */
		playing: string
	}
	warnings: {
		/** Release unused global shortcut keys */
		unusedGlobal: string
		/** Set as the active video for shortcuts. Helpful on pages with multiple videos or to control background videos. */
		selectTooltip: string
		/** Hold shift key for precise control */
		sliderTooltip: string
		/** Requires the $1 shortcut, which must be set up as a browser or menu shortcut */
		captureRequired: string
		/** Javascript shortcuts require Chrome or Edge version 136 or newer */
		jsUpdate: string
		/** Enable 'Allow User Scripts' to use javascript shortcuts */
		jsWarning: string
		/** Enable 'Allow User Scripts' to use javascript URL rules */
		jsWarningRules: string
		/** Enable developer mode to use javascript shortcuts */
		jsWarningEdge: string
		/** Enable developer mode to use javascript URL rules */
		jsWarningRulesEdge: string
	}
	menuLabels: {
		/** Invert page */
		invertPage: string
		/** Grayscale page */
		grayscalePage: string
		/** Video brightness */
		videoBrightness: string
		/** Video contrast */
		videoContrast: string
	}
	header: {
		/** Toggle state */
		powerTooltip: string
		/** Pinned tabs keep their own settings instead of sharing the global context */
		pinTooltip: string
		/** Audio effects */
		audioEffects: string
		/** Video effects */
		videoEffects: string
		/** Settings */
		settingsPage: string
		/** View source */
		github: string
	}
	token: {
		/** Create */
		create: string
		/** Reset */
		reset: string
		/** Duplicate */
		duplicate: string
		/** Back */
		back: string
		/** Delete */
		delete: string
		/** Aspect lock */
		aspectLock: string
		/** Merge both */
		mergeBoth: string
		/** Min */
		min: string
		/** Max */
		max: string
		/** Turn on */
		on: string
		/** Turn off */
		off: string
		/** Toggle */
		toggle: string
		/** Video */
		video: string
		/** Page */
		page: string
		/** Both */
		both: string
		/** Selector */
		selector: string
		/** CSS selector used to find elements to filter. By default it only targets videos, but you can use 'video, img, canvas' to target videos, images and games. */
		selectorTooltip: string
		/** Into window */
		intoPane: string
		/** Turn filters into a floating, draggable window */
		intoPaneTooltip: string
		/** Warning */
		warning: string
		/** Filters */
		filters: string
		/** Transforms */
		transforms: string
		/** Block events */
		blockEvents: string
		/** Will try to block event propagation and default behaviors */
		blockEventsTooltip: string
		/** Color */
		color: string
		/** Size */
		size: string
		/** Rounding */
		rounding: string
		/** Duration */
		duration: string
		/** Offset */
		offset: string
		/** Position */
		position: string
		/** Center */
		center: string
		/** Top left */
		topLeft: string
		/** Top right */
		topRight: string
		/** Bottom left */
		bottomLeft: string
		/** Bottom right */
		bottomRight: string
		/** Animation */
		animation: string
		/** Default */
		default: string
		/** Static */
		static: string
		/** Shrink */
		shrink: string
		/** Implode */
		implode: string
		/** Rotate */
		rotate: string
		/** Rows */
		rows: string
		/** Invalid number */
		invalidNumber: string
		/** Open page */
		openPage: string
		/** Seconds */
		seconds: string
		/** Percent */
		percent: string
		/** Frames */
		frames: string
		/** Show more */
		showMore: string
		/** Assign */
		assign: string
		/** None */
		none: string
		/** Edit */
		edit: string
		/** Customize */
		customize: string
		/** Allow shortcuts on $1 */
		allowShortcuts: string
		/** Allow on $1 */
		allowOn: string
		/** Mode */
		mode: string
		/** Darkness */
		darkness: string
		/** Standard */
		modeStandard: string
		/** Custom color */
		modeCustomColor: string
		/** Custom filter */
		modeCustomFilter: string
		/** Left */
		left: string
		/** Right */
		right: string
		/** Small step */
		smallStep: string
		/** Large step */
		largeStep: string
		/** Move down */
		moveDown: string
		/** Move up */
		moveUp: string
		/** Jump to tab */
		jumpToTab: string
		/** Hide */
		hide: string
	}
	placer: {
		windowBounds: {
			/** Left */
			left: string
			/** Top */
			top: string
			/** Width */
			width: string
			/** Height */
			height: string
		}
		/** Interactive window sizing */
		windowSize: string
		/** Adjust this window's size and location and press Apply */
		windowPrompt: string
		/** Apply */
		apply: string
		/** Cancel */
		cancel: string
	}
	filter: {
		/** Swap video and page filters */
		swap: string
		/** Grayscale */
		grayscale: string
		/** Sepia */
		sepia: string
		/** Hue-rotate */
		hueRotate: string
		/** Contrast */
		contrast: string
		/** Brightness */
		brightness: string
		/** Saturation */
		saturate: string
		/** Invert */
		invert: string
		/** Blur */
		blur: string
		/** Opacity */
		opacity: string
		/** ScaleX */
		scaleX: string
		/** ScaleY */
		scaleY: string
		/** TranslateX */
		translateX: string
		/** TranslateY */
		translateY: string
		/** RotateX */
		rotateX: string
		/** RotateY */
		rotateY: string
		/** RotateZ */
		rotateZ: string
		otherFilters: {
			/** Other filters */
			header: string
			/** Mosaic */
			mosaic: string
			/** Color map */
			colorMatrix: string
			/** RGB */
			rgb: string
			/** Red */
			red: string
			/** Green */
			green: string
			/** Blue */
			blue: string
			/** Custom */
			custom: string
			/** Sharpen */
			sharpen: string
			/** Special */
			special: string
			/** Posterize */
			posterize: string
			/** Blur */
			blur: string
			/** Block X */
			blockX: string
			/** Block Y */
			blockY: string
			/** Detail X */
			detailX: string
			/** Detail Y */
			detailY: string
			/** Stretch X */
			stretchX: string
			/** Stretch Y */
			stretchY: string
			/** Levels */
			levels: string
			/** Amount */
			amount: string
			/** Vertical */
			vertical: string
			/** Horizontal */
			horizontal: string
			/** Presets */
			presets: string
			/** Motion */
			motion: string
			/** Noise */
			noise: string
			/** Multiply */
			multiply: string
			/** Color burn */
			colorBurn: string
			/** Hard light */
			hardLight: string
		}
	}
	command: {
		/** No action */
		nothing: string
		/** It does nothing. It can be used to block shortcut keys. For example, if you keep accidently pressing spacebar, you can set spacebar to do nothing. With this shortcut, you can also configure a delay. This is useful because you can set multiple shortcuts to be triggered by same key and they will run sequentially. For example, invert page with filter, wait 5 seconds, and then reset filters. */
		nothingTooltip: string
		/** Run code */
		runCode: string
		/** Open URL */
		openUrl: string
		/** Speed */
		speed: string
		/** Allow pitch shift */
		speedChangesPitch: string
		/** When enabled, changing speed will also change the pitch of the audio */
		speedChangesPitchTooltip: string
		/** Pin tab */
		pin: string
		/** State */
		state: string
		/** Seek */
		seek: string
		/** Pause */
		pause: string
		/** Mute */
		mute: string
		/** Volume */
		volume: string
		/** Set mark */
		setMark: string
		/** Seek mark */
		seekMark: string
		/** Loop segment */
		loop: string
		/** Repeat the video from the marked position to the current position */
		loopTooltip: string
		/** Skip segment */
		skip: string
		/** Skip a segment of the video between the marked position and current position */
		skipTooltip: string
		/** Fully loop */
		loopEntire: string
		/** Auto-break */
		autoBreak: string
		/** Break loop if you navigate outside the bounds */
		autoBreakTooltip: string
		/** Break skip if you navigate inside it */
		autoBreakTooltipAlt: string
		/** Fullscreen */
		fullscreen: string
		/** Simple */
		nativeTooltip: string
		/** Picture-in-picture */
		PiP: string
		/** FX state */
		fxState: string
		/** FX reset */
		fxReset: string
		/** FX swap */
		fxSwap: string
		/** Filter */
		fxFilter: string
		/** Capture audio */
		afxCapture: string
		/** Pitch */
		afxPitch: string
		/** Volume boost */
		afxGain: string
		/** Delay */
		afxDelay: string
		/** Pan */
		afxPan: string
		/** Mono */
		afxMono: string
		/** Merge audio channels */
		afxMonoTooltip: string
		/** Audio reset */
		afxReset: string
		/** Relative to speed */
		relativeToSpeed: string
		/** Show total duration */
		showNet: string
		/** Draw on page */
		drawPage: string
		/** Fast seek */
		fastSeek: string
		/** Faster but less accurate */
		fastSeekTooltip: string
		/** Show media info */
		mediaInfo: string
		/** Into popup */
		intoPopup: string
		/** Turn current tab into a popup window */
		intoPopupTooltip: string
		/** Darken background */
		cinema: string
		/** Darken the background of the video. To exit out, press on the background or use shortcut again. */
		cinemaTooltip: string
		/** Presets... */
		presets: string
		/** Fast forward */
		temporarySpeed: string
		/** Press and hold to speed up videos */
		temporarySpeedTooltip: string
		/** Toggle speed */
		toggleSpeed: string
		/** Toggle between shortcut speed and the last speed */
		toggleSpeedTooltip: string
		/** Always on */
		alwaysOn: string
		/** Allow the shortcut to enable the extension even if it was disabled from the menu */
		alwaysOnTooltip: string
		/** Mute tab */
		muteTab: string
	}
	options: {
		flags: {
			/** Options */
			header: string
			/** Language */
			language: string
			_languageTooltip?: string
			/** Dark theme */
			darkTheme: string
			/** Use system theme */
			darkThemeSystem: string
			/** Show badge */
			showBadge: string
			/** The badge is the text on the extension icon */
			showBadgeTooltip: string
			/** Show media list */
			showMediaView: string
			/** Show indicator */
			showIndicator: string
			/** The indicator is visual feedback when using shortcuts */
			showIndicatorTooltip: string
			/** Ghost mode */
			ghostMode: string
			/** Prevents websites from detecting playback speed changes. When enabled, it applies to all websites by default. This may cause issues on some sites. Use the gear icon to limit it to specific websites. */
			ghostModeTooltip: string
			/** Pin new tabs */
			pinByDefault: string
			/** Initial context */
			initialContext: string
			/** The starting context for newly pinned tabs */
			initialContextTooltip: string
			/** Global context */
			globalContext: string
			/** Previous tab's context */
			previousContext: string
			/** New context */
			newContext: string
			/** Custom context */
			customContext: string
			/** Saved a snapshot of this tab's current context. Newly created tabs will use this snapshot as an initial state. */
			customContextTooltip: string
			/** Keyboard input */
			keyboardInput: string
			/** Consider switching to Virtual input mode if using a virtual keyboard or a non-QWERTY layout keyboard. This only applies to future shortcut changes and existing shortcuts won't be affected. */
			keyboardInputTooltip: string
			/** QWERTY layout */
			qwerty: string
			/** Virtual */
			virtual: string
			/** Grant permission */
			grantPermission: string
			/** To enable full functionality, including embed video support, this permission must be enabled. For limited functionality, you can enable on a site-by-site basis by right clicking the toolbar icon. */
			grantPermissionTooltip: string
			/** Show speed slider */
			speedSlider: string
			/** Text size */
			textSize: string
			/** Speed presets */
			speedPresets: string
			widget: {
				/** Show circle widget */
				option: string
				/** A circle widget will be shown while videos are visible. - Drag left/right to seek through video. - Drag up/down to adjust playback rate. */
				optionTooltip: string
				/** - Press circle for a few seconds to to move or delete it. */
				movementMobile: string
				/** - With right mouse button, drag circle to move or delete it. */
				movementDesktop: string
				/** Enabled circle widget */
				headerTooltip: string
				/** Auto hide */
				autoHide: string
				/** Fullscreen only */
				fullscreenOnly: string
				/** Only show widget when the video is fullscreen */
				fullscreenOnlyTooltip: string
				/** Press action */
				pressAction: string
				/** Toggle pause */
				togglePause: string
				/** Fixed speed step */
				fixedSpeedStep: string
				/** Always adjust speed by a fixed amount when moving the circle widget */
				fixedSpeedStepTooltip: string
				/** Fixed seek step */
				fixedSeekStep: string
				/** Always seek by a fixed amount of seconds when moving the circle widget */
				fixedSeekStepTooltip: string
				/** Skip forward */
				skipForward: string
				/** Skip backward */
				skipBackward: string
			}
			/** Scan to use on... */
			qrCodeTop: string
			/** Edge for Mobile */
			qrCodeBottom: string
			/** Press and hold to fast forward */
			holdToSpeedUp: string
			/** Press and hold videos to temporarily speed up */
			holdToSpeedUpTooltip: string
			/** Long press duration */
			longPressThreshold: string
			/** The cutoff between regular and long-press shortcuts, in seconds */
			longPressThresholdTooltip: string
			/** Double tap duration */
			doubleTapThreshold: string
			/** Double-tap window in seconds. The second tap must land within this time */
			doubleTapThresholdTooltip: string
		}
		editor: {
			/** Shortcut Editor */
			header: string
			/** Keyboard Shortcuts */
			headerMobile: string
			/** Page Shortcuts */
			pageShortcuts: string
			/** By default, shortcuts are disabled on most websites. */
			shortcutWarningAllow: string
			/** By default, shortcuts are enabled on most websites. */
			shortcutWarningBlock: string
			/** Learn to enable shortcuts for a website. */
			shortcutWarningLearnAllow: string
			/** Learn to disable shortcuts for a website. */
			shortcutWarningLearnBlock: string
			/** Browser Shortcuts */
			browserShortcuts: string
			/** Can be used to control videos while using another app */
			browserShortcutsSub: string
			/** Menu Shortcuts */
			menuShortcuts: string
			/** These shortcuts are shown when you right click on a page */
			menuShortcutsSub: string
			/** Global shortcuts are useful when you want to control video or audio while using another program */
			toggleModeTooltip: string
			/** Menu label */
			menuLabel: string
			/** Multiple trigger modes are supported */
			triggerMode: string
			/** Local shortcuts (default): Flexible shortcut keys. Global shortcuts: Useful when you want to control video or audio while using another application. Context menu: Ideal for seldomly used commands. Right click on the page to trigger them. */
			triggerModeTooltip: string
			/** Local shortcuts (default): Flexible shortcut keys. Context menu: Ideal for seldomly used commands. Right click on the page to trigger them. */
			triggerModeTooltipFf: string
			triggerModes: {
				/** Local shortcuts */
				"0": string
				/** Global shortcuts */
				"1": string
				/** Context menu */
				"2": string
			}
			/** Spacing */
			spacing: string
			/** Reversible */
			reversible: string
			/** Allows setting a second shortcut to reverse the list */
			reversibleTooltip: string
			/** Wraparound */
			wraparound: string
			/** If you go past the start or end, it loops around to the other side */
			wraparoundTooltip: string
			/** Add label */
			addLabel: string
			/** Live scrubbing */
			liveScrubbing: string
			/** Continously preview changes while moving cursor */
			liveScrubbingTooltip: string
			/** Pause while scrubbing */
			pauseWhileScrubbing: string
			adjustModes: {
				/** Set to value */
				"1": string
				/** Adjust by value */
				"2": string
				/** Cycle between list of values */
				"3": string
				/** Interactively set to value */
				"4": string
				/** Interactively adjust by value */
				"5": string
			}
			openModes: {
				/** Foreground tab */
				foregroundTab: string
				/** Background tab */
				backgroundTab: string
				/** New window */
				newWindow: string
				/** New popup */
				newPopup: string
				/** Current tab */
				sameTab: string
			}
			/** Press and hold */
			pressAndHold: string
			/** If enabled, the key must be held down while interactively adjusting the value */
			pressAndHoldTooltip: string
			/** Long press */
			longPress: string
			/** Only trigger when the key is held down for a longer duration */
			longPressTooltip: string
			/** Double tap */
			doubleTap: string
			/** Only trigger when the key is tapped twice in quick succession */
			doubleTapTooltip: string
			/** No repeat */
			noRepeat: string
			/** Shortcut will only run once while holding down a key */
			noRepeatTooltip: string
			/** Click to change */
			keyPickerInput: string
			/** Press new shortcut */
			keyPickerInputTooltip: string
		}
		rules: {
			/** URL Rules */
			header: string
			/** Set title keywords */
			setTitleKeywords: string
			/** Delete title keywords */
			clearTitleKeywords: string
			/** Change title keywords */
			ChangeTitleKeywords: string
			/** Page title must include: */
			pageTitleLabel: string
			/** Specify a comma separated list of terms and at least one must be in the page title. For example, it can be used on Youtube to set speed to 1x for music videos. */
			pageTitleTooltip: string
			/** URL conditions */
			conditions: string
			/** Starts with */
			startsWith: string
			/** Contains */
			contains: string
			/** Regex */
			regex: string
			/** Allowlist */
			allowlist: string
			/** Blocklist */
			blocklist: string
			/** URL rules have changed some values */
			status: string
			/** Strictness */
			strictness: string
			/** Control how frequently the URL rule is applied. 1: Apply only once until no longer matching. 2: Re-apply if domain name is different. 3: Re-apply every page load. 4: Re-apply every time URL changes. */
			strictnessTooltip: string
			headers: {
				/** Websites where shortcuts will work */
				keybindsAllow: string
				/** Websites where shortcuts will be disabled */
				keybindsBlock: string
				/** Shortcuts work on all websites */
				keybindsNeutral: string
				/** Websites where this shortcut will work */
				keybindAllow: string
				/** Websites where this shortcut will be disabled */
				keybindBlock: string
				/** This shortcut works on all websites */
				keybindNeutral: string
				/** Websites where ghost mode will be active */
				ghostAllow: string
				/** Websites where ghost mode will be inactive */
				ghostBlock: string
				/** Ghost mode is active on all websites */
				ghostNeutral: string
				/** Websites where this rule will apply */
				ruleAllow: string
				/** Websites where this rule won't apply */
				ruleBlock: string
				/** This rule won't apply on any website */
				ruleNeutral: string
			}
		}
		help: {
			/** Help */
			header: string
			/** Have issues or a suggestion? */
			issuePrompt: string
			/** Provide feedback on Github */
			issueDirective: string
			/** Export */
			export: string
			/** Import */
			import: string
			/** Are you sure? */
			areYouSure: string
			/** Copy settings */
			copy: string
			/** Copied! */
			copied: string
			/** Paste settings */
			paste: string
			/** Export settings */
			exportTooltip: string
			/** Import settings */
			importTooltip: string
		}
		popup: {
			/** Optional: Enable keyboard shortcuts on this website */
			enableShortcutsMessage: string
		}
	}
	pageDraw: {
		_labelScale?: number
		_fontScale?: number
		/** Draw */
		draw: string
		/** Erase */
		erase: string
		/** Select */
		select: string
		/** Interact with the webpage */
		selectTooltip: string
		/** Flood page */
		floodPage: string
		/** Set background */
		setBackground: string
		/** Clear background */
		clearBackground: string
		/** Some useful shortcuts 1. Erase with right mouse button. 2. Draw lines with shift click. 3. Toggle between $1 and $2 mode using Caps Lock 4. To adjust eraser size: hold down the middle mouse button and drag left or right. 5. To adjust brush size: hold down the middle mouse button and drag up or down. 6. Right click on a color for more options. */
		tips: string
	}
}
